import sanitizeHtml from "sanitize-html";

/**
 * Analytics beacons dressed as images. The Conversation leads every feed item
 * with one, and using it as the card artwork produces a blank or broken image.
 */
export const TRACKING_PIXEL =
  /counter\.|\/count\.gif|feedburner|\bpixel\b|\/track(ing)?[\/.]|beacon|stats?\.|\/pv\.gif|doubleclick|scorecardresearch/i;

export function isTrackingPixel(url: string) {
  return !url || TRACKING_PIXEL.test(url);
}

/**
 * Feeds hand out whatever thumbnail their CMS defaults to — the BBC's is 240px
 * wide, which looks awful at card size. Where a CDN encodes the width in the
 * path, ask for a bigger rendition of the same image.
 */
export function upgradeImage(url: string): string {
  if (!url) return url;

  // ichef.bbci.co.uk/ace/standard/240/... → .../976/...
  const bbc = url.replace(
    /(ichef\.bbci\.co\.uk\/[a-z]+\/[a-z]+\/)(\d{2,4})(\/)/,
    (_m, prefix, width, suffix) =>
      Number(width) < 976 ? `${prefix}976${suffix}` : `${prefix}${width}${suffix}`
  );
  if (bbc !== url) return bbc;

  /*
   * WordPress writes resized copies as "photo-300x200.jpg" beside the original
   * "photo.jpg". Feeds often advertise a small copy, so ask for the original.
   */
  const wp = url.replace(
    /-(\d{2,4})x(\d{2,4})(\.(?:jpe?g|png|webp|avif))/i,
    (match, w: string, _h: string, ext: string) =>
      Number(w) < 1200 ? ext : match
  );
  if (wp !== url) return wp;

  // Generic "…/640x360/…" style paths.
  return url.replace(
    /\/(\d{3,4})x(\d{3,4})\//,
    (match, w: string, h: string) => {
      const width = Number(w);
      if (width >= 900) return match;
      const scale = 1200 / width;
      return `/1200x${Math.round(Number(h) * scale)}/`;
    }
  );
}

/** Strip the boilerplate publishers append to their own feed items. */
const BOILERPLATE = [
  /<p>\s*The post .*?appeared first on .*?<\/p>/gis,
  /<p>[^<]*(continue reading|read more|read the full)[^<]*<\/p>/gi,
  /<div[^>]*(sharedaddy|share-buttons|feedflare|social)[^>]*>.*?<\/div>/gis,
  /<a[^>]*feedburner[^>]*>.*?<\/a>/gis,
];

/**
 * Everything a publisher bolts onto the end of the piece — newsletter pitches,
 * "add us as a preferred source" badges, comment scaffolding, share widgets.
 * These always trail the article, so the whole tail gets cut at the first hit
 * rather than trying to match each block individually.
 */
const TRAILING_JUNK = [
  /want to stay up to date/i,
  /preferred source/i,
  /view\s+\d+\s+comments?/i,
  /loading comments/i,
  /forum view/i,
  /\bshare this:/i,
  /\blike this:/i,
  /subscribe to (our|the) newsletter/i,
  /sign up for (our|the)/i,
  /follow us on/i,
  /this article (originally )?appeared/i,
  /you might also like/i,
  /related(:| articles| reading)/i,
];

/**
 * Interface scaffolding that survives extraction: audio-player fallbacks,
 * "listen to article" controls, unrendered template placeholders, AI notices,
 * share prompts. Matched against a block's own text, anywhere in the piece.
 */
const JUNK_BLOCKS = [
  /your browser does not support/i,
  /listen to (this )?article/i,
  /this content is generated by google ai/i,
  /generative ai is experimental/i,
  /^\s*advertisement\s*$/i,
  /enable javascript/i,
  /^\s*\d+\s*min(ute)?s?\s+read\s*$/i,
  /^\s*(share|tweet|email this|print|copy link|save)\s*$/i,
  /skip to (main )?content/i,
  /(sign|log) in to continue/i,
  /^\s*\[\[[^\]]*\]\]/,
  /^\s*(image|photo|video|credit|caption):\s*$/i,
];

function removeJunkBlocks(html: string) {
  const withoutBlocks = html.replace(
    /<(p|div|span|li|h[1-6])\b[^>]*>([\s\S]*?)<\/\1>/gi,
    (match, _tag: string, inner: string) => {
      const text = inner.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
      // Keep empty wrappers — they may hold an image the sanitizer will judge.
      if (!text) return match;
      return JUNK_BLOCKS.some((pattern) => pattern.test(text)) ? "" : match;
    }
  );

  // Unrendered template tokens, e.g. "[[duration]] minutes".
  return withoutBlocks.replace(/\[\[[^\]]{1,40}\]\]/g, "");
}

/**
 * Only the closing stretch is treated as the tail. These same phrases turn up
 * mid-article — a "related:" aside three paragraphs in is not the end of the
 * piece, and cutting there discards the reporting.
 */
const TAIL_ZONE = 0.55;

function trimTrailingJunk(html: string) {
  let cut = html.length;
  const threshold = html.length * TAIL_ZONE;

  for (const pattern of TRAILING_JUNK) {
    const match = pattern.exec(html);
    if (!match || match.index < threshold) continue;
    // Rewind to the start of the block that contains the marker, so the cut
    // doesn't leave a half-open paragraph behind.
    const blockStart = html.lastIndexOf("<", match.index);
    const start = blockStart === -1 ? match.index : blockStart;
    if (start < cut) cut = start;
  }

  return cut === html.length ? html : html.slice(0, cut);
}

/**
 * Feed HTML is untrusted, so everything is run through an allowlist before it
 * can reach the page. Layout-bearing tags survive; scripts, styles, iframes,
 * event handlers and tracking pixels do not.
 */
export function sanitizeArticleHtml(html: string): string {
  if (!html) return "";

  let cleaned = removeJunkBlocks(trimTrailingJunk(html));
  for (const pattern of BOILERPLATE) cleaned = cleaned.replace(pattern, "");

  return sanitizeHtml(cleaned, {
    allowedTags: [
      "p", "br", "strong", "b", "em", "i", "u", "s", "blockquote", "q",
      "h2", "h3", "h4", "ul", "ol", "li", "figure", "figcaption", "img",
      "a", "code", "pre", "hr", "table", "thead", "tbody", "tr", "th", "td",
    ],
    allowedAttributes: {
      a: ["href", "title"],
      img: ["src", "alt", "title"],
      // Spec tables rely on merged cells; stripping these misaligns every row.
      td: ["colspan", "rowspan"],
      th: ["colspan", "rowspan", "scope"],
    },
    allowedSchemes: ["http", "https"],
    transformTags: {
      a: (tagName, attribs) => ({
        tagName,
        attribs: { ...attribs, target: "_blank", rel: "noreferrer nofollow" },
      }),
      img: (tagName, attribs) => ({
        tagName,
        attribs: { ...attribs, src: upgradeImage(attribs.src ?? ""), loading: "lazy" },
      }),
    },
    exclusiveFilter: (frame) =>
      // Tracking pixels.
      (frame.tag === "img" &&
        (TRACKING_PIXEL.test(frame.attribs.src ?? "") ||
          /trademark|\btm[-_.]/i.test(frame.attribs.src ?? ""))) ||
      // Trademark and superscript glyphs shipped as images (Samsung does this).
      (frame.tag === "img" && /^\s*(tm|™|®|\*)\s*$/i.test(frame.attribs.alt ?? "")) ||
      // Footnote reference links, which point at notes the feed doesn't include.
      (frame.tag === "a" && /^\[?\d{1,3}\]?$/.test(frame.text.trim())) ||
      // Wrappers left empty by the filters above.
      (["p", "li", "blockquote"].includes(frame.tag) &&
        !frame.text.trim() &&
        !frame.mediaChildren.length),
  }).trim();
}

/**
 * Plenty of feeds ship no artwork at all (Apple Newsroom, Electrek, Nature).
 * The article page itself always carries an og:image, so fetch that instead —
 * it is also full size rather than a CMS thumbnail.
 */
export async function fetchOgImage(url: string): Promise<string> {
  // Google News links are redirect stubs; there is nothing to read.
  if (/news\.google\.com/i.test(url)) return "";

  try {
    const res = await fetch(url, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36",
      },
      next: { revalidate: 86400 },
    });
    if (!res.ok) return "";

    // The metadata lives in <head>, so the first slice of the document is plenty.
    const html = (await res.text()).slice(0, 120_000);
    const match =
      html.match(/<meta[^>]+property=["']og:image(?::url)?["'][^>]*content=["']([^"']+)["']/i) ??
      html.match(/<meta[^>]+content=["']([^"']+)["'][^>]*property=["']og:image(?::url)?["']/i) ??
      html.match(/<meta[^>]+name=["']twitter:image["'][^>]*content=["']([^"']+)["']/i);

    const found = match?.[1]?.trim() ?? "";
    return found.startsWith("http") ? upgradeImage(found) : "";
  } catch {
    return "";
  }
}

const LAUNCH_PREFIX = /^(introducing|announcing|meet|say hello to|presenting|unveiling)\s+/i;
const FIRST_PERSON = /\b(our|ours|we|we're|we’re|we've|we’ve|us)\b/i;

/**
 * Vendor newsrooms write in the first person — "Introducing WeatherNext 3, our
 * most advanced model". A front page needs the editorial third person, so those
 * headlines get re-voiced with the company as the subject.
 */
export function editorialiseHeadline(
  headline: string,
  source: string,
  firstParty: boolean
): string {
  const isLaunchPost = LAUNCH_PREFIX.test(headline);
  const isFirstPerson = FIRST_PERSON.test(headline);
  if (!isLaunchPost && !(firstParty && isFirstPerson)) return headline;

  let out = isLaunchPost ? headline.replace(LAUNCH_PREFIX, "") : headline;

  out = out
    .replace(/\bwe['’]re\b/gi, `${source} is`)
    .replace(/\bwe['’]ve\b/gi, `${source} has`)
    .replace(/\bwe\b/gi, source)
    .replace(/\bour\b/gi, "its")
    .replace(/\bours\b/gi, "its")
    .replace(/\bus\b/gi, "it");

  // Give a de-prefixed launch post a subject and a verb.
  if (isLaunchPost && !out.toLowerCase().startsWith(source.toLowerCase())) {
    out = `${source} unveils ${out}`;
  }

  return out.replace(/\s+/g, " ").trim();
}

/**
 * CDNs rename the same photograph per rendition, so compare on the filename
 * with size suffixes and extension stripped rather than the whole URL.
 */
function imageKey(url: string) {
  try {
    const file = new URL(url).pathname.split("/").pop() ?? "";
    return file
      .replace(/[-_]\d{2,4}x\d{2,4}(?=\.|$)/, "")
      .replace(/\.(jpe?g|png|webp|avif|gif)$/i, "")
      .toLowerCase();
  } catch {
    return url.toLowerCase();
  }
}

/**
 * The story page already shows the lead image above the headline, and most
 * articles open with that same photograph. Drop the body's copy of it.
 */
export function removeDuplicateLeadImage(html: string, heroUrl: string): string {
  if (!html || !heroUrl) return html;

  const key = imageKey(heroUrl);
  const IMAGE_BLOCK =
    /<figure\b[^>]*>[\s\S]*?<\/figure>|<p\b[^>]*>\s*<img\b[^>]*>\s*<\/p>|<img\b[^>]*>/gi;

  // First pass: the same photograph, wherever it appears.
  let removed = false;
  let out = html.replace(IMAGE_BLOCK, (match) => {
    if (removed) return match;
    const src = match.match(/src=["']([^"']+)["']/i)?.[1];
    if (src && key && imageKey(src) === key) {
      removed = true;
      return "";
    }
    return match;
  });
  if (removed) return out;

  /*
   * Second pass: publishers serve the lead image at a different size, from a
   * different CDN path, or renamed entirely, so URL matching alone misses it.
   * An article that opens on an image, with a hero already displayed above the
   * headline, is showing that same picture twice — drop the opening one.
   */
  IMAGE_BLOCK.lastIndex = 0;
  const first = IMAGE_BLOCK.exec(out);
  if (!first) return out;

  const preceding = out.slice(0, first.index).replace(/<[^>]*>/g, " ").trim();
  const OPENING_PROSE = 320; // roughly a paragraph
  if (preceding.length <= OPENING_PROSE) {
    out = out.slice(0, first.index) + out.slice(first.index + first[0].length);
  }

  return out;
}

/**
 * Feeds advertise thumbnails in the URL — "/150x100/", "?w=320", "-thumb".
 * Anything that small looks broken at card size, so it is treated as no image
 * at all and replaced by the article's own og:image.
 */
export function looksLowResolution(url: string): boolean {
  if (!url) return false;

  const dims = url.match(/[/_-](\d{2,4})x(\d{2,4})[/_.]/);
  if (dims && Number(dims[1]) < 500) return true;

  const width = url.match(/[?&](?:w|width|size)=(\d{2,4})/);
  if (width && Number(width[1]) < 500) return true;

  return /thumb(nail)?|[/_-]small[/_.]|[/_-]tn[/_.]|\/s\d{2,3}\//i.test(url);
}

/** Rough word count, used to decide whether a feed gave us a real article. */
export function wordCount(html: string) {
  return html.replace(/<[^>]*>/g, " ").split(/\s+/).filter(Boolean).length;
}
